/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_winMain (void)
{
  GtkWidget *winMain;
  GdkPixbuf *winMain_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *mbMain;
  GtkWidget *mnuMessenger;
  GtkWidget *mnuMessenger_menu;
  GtkWidget *mnuMessengerConnect;
  GtkWidget *image26;
  GtkWidget *mnuDisconnect;
  GtkWidget *image27;
  GtkWidget *mnuMessengerRefresh;
  GtkWidget *image28;
  GtkWidget *separator2;
  GtkWidget *mnuPreferences;
  GtkWidget *separatormenuitem1;
  GtkWidget *mnuMessengerQuit;
  GtkWidget *mnuHelp;
  GtkWidget *mnuHelp_menu;
  GtkWidget *mnuHelpAbout;
  GtkWidget *image29;
  GtkWidget *tbMain;
  gint tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *butSendIM;
  GtkWidget *tbAddBuddy;
  GtkWidget *scwBuddyList;
  GtkWidget *tvBuddyList;
  GtkWidget *hbox2;
  GtkWidget *lblStatus;
  GtkWidget *cboStatus;
  GtkWidget *sbMain;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  winMain = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (winMain), _("Yux"));
  gtk_window_set_default_size (GTK_WINDOW (winMain), 200, 300);
  winMain_icon_pixbuf = create_pixbuf ("yux.png");
  if (winMain_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (winMain), winMain_icon_pixbuf);
      gdk_pixbuf_unref (winMain_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (winMain), vbox1);

  mbMain = gtk_menu_bar_new ();
  gtk_widget_show (mbMain);
  gtk_box_pack_start (GTK_BOX (vbox1), mbMain, FALSE, FALSE, 0);

  mnuMessenger = gtk_menu_item_new_with_mnemonic (_("_Messenger"));
  gtk_widget_show (mnuMessenger);
  gtk_container_add (GTK_CONTAINER (mbMain), mnuMessenger);

  mnuMessenger_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mnuMessenger), mnuMessenger_menu);

  mnuMessengerConnect = gtk_image_menu_item_new_with_mnemonic (_("_Connect"));
  gtk_widget_show (mnuMessengerConnect);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), mnuMessengerConnect);
  gtk_widget_add_accelerator (mnuMessengerConnect, "activate", accel_group,
                              GDK_O, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image26 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image26);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuMessengerConnect), image26);

  mnuDisconnect = gtk_image_menu_item_new_with_mnemonic (_("_Disconnect"));
  gtk_widget_show (mnuDisconnect);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), mnuDisconnect);
  gtk_widget_add_accelerator (mnuDisconnect, "activate", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image27 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image27);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuDisconnect), image27);

  mnuMessengerRefresh = gtk_image_menu_item_new_with_mnemonic (_("_Refresh"));
  gtk_widget_show (mnuMessengerRefresh);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), mnuMessengerRefresh);
  gtk_widget_add_accelerator (mnuMessengerRefresh, "activate", accel_group,
                              GDK_R, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image28 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image28);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuMessengerRefresh), image28);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  mnuPreferences = gtk_image_menu_item_new_from_stock ("gtk-preferences", accel_group);
  gtk_widget_show (mnuPreferences);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), mnuPreferences);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  mnuMessengerQuit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (mnuMessengerQuit);
  gtk_container_add (GTK_CONTAINER (mnuMessenger_menu), mnuMessengerQuit);

  mnuHelp = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (mnuHelp);
  gtk_container_add (GTK_CONTAINER (mbMain), mnuHelp);

  mnuHelp_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mnuHelp), mnuHelp_menu);

  mnuHelpAbout = gtk_image_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (mnuHelpAbout);
  gtk_container_add (GTK_CONTAINER (mnuHelp_menu), mnuHelpAbout);

  image29 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image29);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuHelpAbout), image29);

  tbMain = gtk_toolbar_new ();
  gtk_widget_show (tbMain);
  gtk_box_pack_start (GTK_BOX (vbox1), tbMain, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (tbMain), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (tbMain));

  tmp_image = gtk_image_new_from_stock ("gtk-justify-fill", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  butSendIM = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Send IM"));
  gtk_widget_show (butSendIM);
  gtk_container_add (GTK_CONTAINER (tbMain), butSendIM);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tbAddBuddy = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add Buddy"));
  gtk_widget_show (tbAddBuddy);
  gtk_container_add (GTK_CONTAINER (tbMain), tbAddBuddy);

  scwBuddyList = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scwBuddyList);
  gtk_box_pack_start (GTK_BOX (vbox1), scwBuddyList, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scwBuddyList), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scwBuddyList), GTK_SHADOW_IN);

  tvBuddyList = gtk_tree_view_new ();
  gtk_widget_show (tvBuddyList);
  gtk_container_add (GTK_CONTAINER (scwBuddyList), tvBuddyList);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (tvBuddyList), FALSE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 0);

  lblStatus = gtk_label_new (_("Status: "));
  gtk_widget_show (lblStatus);
  gtk_box_pack_start (GTK_BOX (hbox2), lblStatus, FALSE, FALSE, 0);

  cboStatus = gtk_combo_box_new_text ();
  gtk_widget_show (cboStatus);
  gtk_box_pack_start (GTK_BOX (hbox2), cboStatus, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("Available"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("Be Right Back"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("Busy"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("Not At Desk"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("On The Phone"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("Invisible"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cboStatus), _("Custom ..."));

  sbMain = gtk_statusbar_new ();
  gtk_widget_show (sbMain);
  gtk_box_pack_start (GTK_BOX (vbox1), sbMain, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) winMain, "show",
                    G_CALLBACK (on_winMain_show),
                    NULL);
  g_signal_connect ((gpointer) winMain, "delete_event",
                    G_CALLBACK (on_winMain_delete_event),
                    NULL);
  g_signal_connect ((gpointer) mnuMessengerConnect, "activate",
                    G_CALLBACK (on_mnuMessengerConnect_activate),
                    NULL);
  g_signal_connect ((gpointer) mnuDisconnect, "activate",
                    G_CALLBACK (on_mnuDisconnect_activate),
                    NULL);
  g_signal_connect ((gpointer) mnuMessengerRefresh, "activate",
                    G_CALLBACK (on_mnuMessengerRefresh_activate),
                    NULL);
  g_signal_connect ((gpointer) mnuPreferences, "activate",
                    G_CALLBACK (on_mnuPreferences_activate),
                    NULL);
  g_signal_connect ((gpointer) mnuMessengerQuit, "activate",
                    G_CALLBACK (on_mnuMessengerQuit_activate),
                    NULL);
  g_signal_connect ((gpointer) mnuHelpAbout, "activate",
                    G_CALLBACK (on_mnuHelpAbout_activate),
                    NULL);
  g_signal_connect ((gpointer) butSendIM, "clicked",
                    G_CALLBACK (on_butSendIM_clicked),
                    NULL);
  g_signal_connect ((gpointer) tbAddBuddy, "clicked",
                    G_CALLBACK (on_tbAddBuddy_clicked),
                    NULL);
  g_signal_connect ((gpointer) tvBuddyList, "row_activated",
                    G_CALLBACK (on_tvBuddyList_row_activated),
                    NULL);
  g_signal_connect ((gpointer) cboStatus, "changed",
                    G_CALLBACK (on_cboStatus_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (winMain, winMain, "winMain");
  GLADE_HOOKUP_OBJECT (winMain, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (winMain, mbMain, "mbMain");
  GLADE_HOOKUP_OBJECT (winMain, mnuMessenger, "mnuMessenger");
  GLADE_HOOKUP_OBJECT (winMain, mnuMessenger_menu, "mnuMessenger_menu");
  GLADE_HOOKUP_OBJECT (winMain, mnuMessengerConnect, "mnuMessengerConnect");
  GLADE_HOOKUP_OBJECT (winMain, image26, "image26");
  GLADE_HOOKUP_OBJECT (winMain, mnuDisconnect, "mnuDisconnect");
  GLADE_HOOKUP_OBJECT (winMain, image27, "image27");
  GLADE_HOOKUP_OBJECT (winMain, mnuMessengerRefresh, "mnuMessengerRefresh");
  GLADE_HOOKUP_OBJECT (winMain, image28, "image28");
  GLADE_HOOKUP_OBJECT (winMain, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (winMain, mnuPreferences, "mnuPreferences");
  GLADE_HOOKUP_OBJECT (winMain, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (winMain, mnuMessengerQuit, "mnuMessengerQuit");
  GLADE_HOOKUP_OBJECT (winMain, mnuHelp, "mnuHelp");
  GLADE_HOOKUP_OBJECT (winMain, mnuHelp_menu, "mnuHelp_menu");
  GLADE_HOOKUP_OBJECT (winMain, mnuHelpAbout, "mnuHelpAbout");
  GLADE_HOOKUP_OBJECT (winMain, image29, "image29");
  GLADE_HOOKUP_OBJECT (winMain, tbMain, "tbMain");
  GLADE_HOOKUP_OBJECT (winMain, butSendIM, "butSendIM");
  GLADE_HOOKUP_OBJECT (winMain, tbAddBuddy, "tbAddBuddy");
  GLADE_HOOKUP_OBJECT (winMain, scwBuddyList, "scwBuddyList");
  GLADE_HOOKUP_OBJECT (winMain, tvBuddyList, "tvBuddyList");
  GLADE_HOOKUP_OBJECT (winMain, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (winMain, lblStatus, "lblStatus");
  GLADE_HOOKUP_OBJECT (winMain, cboStatus, "cboStatus");
  GLADE_HOOKUP_OBJECT (winMain, sbMain, "sbMain");

  gtk_window_add_accel_group (GTK_WINDOW (winMain), accel_group);

  return winMain;
}

GtkWidget*
create_dlgLogin (void)
{
  GtkWidget *dlgLogin;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *lblUsername;
  GtkWidget *lblPassword;
  GtkWidget *txtUsername;
  GtkWidget *txtPassword;
  GtkWidget *chkRemember;
  GtkWidget *chkInvisible;
  GtkWidget *expander1;
  GtkWidget *table2;
  GtkWidget *lblHost;
  GtkWidget *lblPort;
  GtkWidget *txtHost;
  GtkWidget *txtPort;
  GtkWidget *lblOptions;
  GtkWidget *dialog_action_area;
  GtkWidget *butSignIn;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image6;
  GtkWidget *label3;
  GtkWidget *butCancel;

  dlgLogin = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlgLogin), _("Sign In"));
  gtk_window_set_type_hint (GTK_WINDOW (dlgLogin), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dlgLogin)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox2, TRUE, TRUE, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, TRUE, TRUE, 0);

  lblUsername = gtk_label_new_with_mnemonic (_("_Username"));
  gtk_widget_show (lblUsername);
  gtk_table_attach (GTK_TABLE (table1), lblUsername, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblUsername), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblUsername), 2, 0);

  lblPassword = gtk_label_new_with_mnemonic (_("_Password"));
  gtk_widget_show (lblPassword);
  gtk_table_attach (GTK_TABLE (table1), lblPassword, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblPassword), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblPassword), 2, 0);

  txtUsername = gtk_entry_new ();
  gtk_widget_show (txtUsername);
  gtk_table_attach (GTK_TABLE (table1), txtUsername, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (txtUsername), 255);
  gtk_entry_set_activates_default (GTK_ENTRY (txtUsername), TRUE);

  txtPassword = gtk_entry_new ();
  gtk_widget_show (txtPassword);
  gtk_table_attach (GTK_TABLE (table1), txtPassword, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (txtPassword), 255);
  gtk_entry_set_visibility (GTK_ENTRY (txtPassword), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (txtPassword), TRUE);

  chkRemember = gtk_check_button_new_with_mnemonic (_("_Remember ID and Password"));
  gtk_widget_show (chkRemember);
  gtk_box_pack_start (GTK_BOX (vbox2), chkRemember, FALSE, FALSE, 0);

  chkInvisible = gtk_check_button_new_with_mnemonic (_("_Invisible"));
  gtk_widget_show (chkInvisible);
  gtk_box_pack_start (GTK_BOX (vbox2), chkInvisible, FALSE, FALSE, 0);

  expander1 = gtk_expander_new (NULL);
  gtk_widget_show (expander1);
  gtk_box_pack_start (GTK_BOX (vbox2), expander1, TRUE, TRUE, 0);

  table2 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (expander1), table2);

  lblHost = gtk_label_new_with_mnemonic (_("_Host"));
  gtk_widget_show (lblHost);
  gtk_table_attach (GTK_TABLE (table2), lblHost, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblHost), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblHost), 2, 0);

  lblPort = gtk_label_new_with_mnemonic (_("Po_rt"));
  gtk_widget_show (lblPort);
  gtk_table_attach (GTK_TABLE (table2), lblPort, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblPort), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblPort), 2, 0);

  txtHost = gtk_entry_new ();
  gtk_widget_show (txtHost);
  gtk_table_attach (GTK_TABLE (table2), txtHost, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  txtPort = gtk_entry_new ();
  gtk_widget_show (txtPort);
  gtk_table_attach (GTK_TABLE (table2), txtPort, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (txtPort), 5);

  lblOptions = gtk_label_new_with_mnemonic (_("_Options"));
  gtk_widget_show (lblOptions);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander1), lblOptions);

  dialog_action_area = GTK_DIALOG (dlgLogin)->action_area;
  gtk_widget_show (dialog_action_area);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area), GTK_BUTTONBOX_SPREAD);

  butSignIn = gtk_button_new ();
  gtk_widget_show (butSignIn);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgLogin), butSignIn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (butSignIn, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (butSignIn), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox1), image6, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("_Sign In"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (label3, GTK_CAN_DEFAULT);

  butCancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (butCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgLogin), butCancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (butCancel, GTK_CAN_DEFAULT);

  gtk_label_set_mnemonic_widget (GTK_LABEL (lblUsername), txtUsername);
  gtk_label_set_mnemonic_widget (GTK_LABEL (lblPassword), txtPassword);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgLogin, dlgLogin, "dlgLogin");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgLogin, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dlgLogin, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dlgLogin, table1, "table1");
  GLADE_HOOKUP_OBJECT (dlgLogin, lblUsername, "lblUsername");
  GLADE_HOOKUP_OBJECT (dlgLogin, lblPassword, "lblPassword");
  GLADE_HOOKUP_OBJECT (dlgLogin, txtUsername, "txtUsername");
  GLADE_HOOKUP_OBJECT (dlgLogin, txtPassword, "txtPassword");
  GLADE_HOOKUP_OBJECT (dlgLogin, chkRemember, "chkRemember");
  GLADE_HOOKUP_OBJECT (dlgLogin, chkInvisible, "chkInvisible");
  GLADE_HOOKUP_OBJECT (dlgLogin, expander1, "expander1");
  GLADE_HOOKUP_OBJECT (dlgLogin, table2, "table2");
  GLADE_HOOKUP_OBJECT (dlgLogin, lblHost, "lblHost");
  GLADE_HOOKUP_OBJECT (dlgLogin, lblPort, "lblPort");
  GLADE_HOOKUP_OBJECT (dlgLogin, txtHost, "txtHost");
  GLADE_HOOKUP_OBJECT (dlgLogin, txtPort, "txtPort");
  GLADE_HOOKUP_OBJECT (dlgLogin, lblOptions, "lblOptions");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgLogin, dialog_action_area, "dialog_action_area");
  GLADE_HOOKUP_OBJECT (dlgLogin, butSignIn, "butSignIn");
  GLADE_HOOKUP_OBJECT (dlgLogin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (dlgLogin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dlgLogin, image6, "image6");
  GLADE_HOOKUP_OBJECT (dlgLogin, label3, "label3");
  GLADE_HOOKUP_OBJECT (dlgLogin, butCancel, "butCancel");

  gtk_widget_grab_default (butSignIn);
  return dlgLogin;
}

GtkWidget*
create_winIM (void)
{
  GtkWidget *winIM;
  GdkPixbuf *winIM_icon_pixbuf;
  GtkWidget *vbox3;
  GtkWidget *mnuIM;
  GtkWidget *mnuConversation;
  GtkWidget *mnuConversation_menu;
  GtkWidget *mnuConversationSave;
  GtkWidget *separatormenuitem2;
  GtkWidget *mnuConversationQuit;
  GtkWidget *menuitem2;
  GtkWidget *menuitem3;
  GtkWidget *scwChat;
  GtkWidget *txtChat;
  GtkWidget *tbIMAttrib;
  gint tmp_toolbar_icon_size;
  GtkWidget *toolitem11;
  GtkWidget *butIMSendFile;
  GtkWidget *alignment2;
  GtkWidget *hbox8;
  GtkWidget *image18;
  GtkWidget *label9;
  GtkWidget *toolitem14;
  GtkWidget *butImInvite;
  GtkWidget *alignment3;
  GtkWidget *hbox9;
  GtkWidget *image19;
  GtkWidget *label10;
  GtkWidget *separatortoolitem11;
  GtkWidget *toolitem8;
  GtkWidget *butSmiley;
  GtkWidget *image20;
  GtkWidget *toolitem9;
  GtkWidget *butIMFont;
  GtkWidget *image12;
  GtkWidget *toolitem10;
  GtkWidget *butIMBuzz;
  GtkWidget *image13;
  GtkWidget *separatortoolitem12;
  GtkWidget *toolitem12;
  GtkWidget *butIMAddBuddy;
  GtkWidget *image15;
  GtkWidget *toolitem13;
  GtkWidget *butIgnore;
  GtkWidget *image16;
  GtkWidget *hbox3;
  GtkWidget *scwIMSend;
  GtkWidget *txtIMSend;
  GtkWidget *butIMSend;
  GtkWidget *sbIM;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  winIM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (winIM), _("IM"));
  gtk_window_set_default_size (GTK_WINDOW (winIM), 400, 300);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (winIM), TRUE);
  winIM_icon_pixbuf = create_pixbuf ("yux.png");
  if (winIM_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (winIM), winIM_icon_pixbuf);
      gdk_pixbuf_unref (winIM_icon_pixbuf);
    }

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (winIM), vbox3);

  mnuIM = gtk_menu_bar_new ();
  gtk_widget_show (mnuIM);
  gtk_box_pack_start (GTK_BOX (vbox3), mnuIM, FALSE, FALSE, 0);

  mnuConversation = gtk_menu_item_new_with_mnemonic (_("_Conversation"));
  gtk_widget_show (mnuConversation);
  gtk_container_add (GTK_CONTAINER (mnuIM), mnuConversation);

  mnuConversation_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mnuConversation), mnuConversation_menu);

  mnuConversationSave = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (mnuConversationSave);
  gtk_container_add (GTK_CONTAINER (mnuConversation_menu), mnuConversationSave);

  separatormenuitem2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem2);
  gtk_container_add (GTK_CONTAINER (mnuConversation_menu), separatormenuitem2);
  gtk_widget_set_sensitive (separatormenuitem2, FALSE);

  mnuConversationQuit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (mnuConversationQuit);
  gtk_container_add (GTK_CONTAINER (mnuConversation_menu), mnuConversationQuit);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (mnuIM), menuitem2);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (mnuIM), menuitem3);

  scwChat = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scwChat);
  gtk_box_pack_start (GTK_BOX (vbox3), scwChat, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scwChat), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scwChat), GTK_SHADOW_IN);

  txtChat = gtk_text_view_new ();
  gtk_widget_show (txtChat);
  gtk_container_add (GTK_CONTAINER (scwChat), txtChat);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (txtChat), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (txtChat), GTK_WRAP_WORD);

  tbIMAttrib = gtk_toolbar_new ();
  gtk_widget_show (tbIMAttrib);
  gtk_box_pack_start (GTK_BOX (vbox3), tbIMAttrib, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (tbIMAttrib), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (tbIMAttrib));

  toolitem11 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem11);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem11);

  butIMSendFile = gtk_button_new ();
  gtk_widget_show (butIMSendFile);
  gtk_container_add (GTK_CONTAINER (toolitem11), butIMSendFile);
  gtk_tooltips_set_tip (tooltips, butIMSendFile, _("Send File"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butIMSendFile), GTK_RELIEF_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (butIMSendFile), alignment2);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox8);

  image18 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox8), image18, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Send File"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox8), label9, FALSE, FALSE, 0);

  toolitem14 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem14);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem14);

  butImInvite = gtk_button_new ();
  gtk_widget_show (butImInvite);
  gtk_container_add (GTK_CONTAINER (toolitem14), butImInvite);
  gtk_tooltips_set_tip (tooltips, butImInvite, _("Invite to Conference"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butImInvite), GTK_RELIEF_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (butImInvite), alignment3);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox9);

  image19 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox9), image19, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Invite"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox9), label10, FALSE, FALSE, 0);

  separatortoolitem11 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem11);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), separatortoolitem11);

  toolitem8 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem8);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem8);

  butSmiley = gtk_button_new ();
  gtk_widget_show (butSmiley);
  gtk_container_add (GTK_CONTAINER (toolitem8), butSmiley);
  gtk_tooltips_set_tip (tooltips, butSmiley, _("Insert Smiley"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butSmiley), GTK_RELIEF_NONE);

  image20 = create_pixmap (winIM, "emote.gif");
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (butSmiley), image20);
  gtk_widget_set_size_request (image20, 20, 20);

  toolitem9 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem9);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem9);

  butIMFont = gtk_button_new ();
  gtk_widget_show (butIMFont);
  gtk_container_add (GTK_CONTAINER (toolitem9), butIMFont);
  gtk_tooltips_set_tip (tooltips, butIMFont, _("Select Font Properties"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butIMFont), GTK_RELIEF_NONE);

  image12 = gtk_image_new_from_stock ("gtk-select-font", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (butIMFont), image12);

  toolitem10 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem10);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem10);

  butIMBuzz = gtk_button_new ();
  gtk_widget_show (butIMBuzz);
  gtk_container_add (GTK_CONTAINER (toolitem10), butIMBuzz);
  gtk_tooltips_set_tip (tooltips, butIMBuzz, _("Buzz User"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butIMBuzz), GTK_RELIEF_NONE);

  image13 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (butIMBuzz), image13);

  separatortoolitem12 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem12);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), separatortoolitem12);

  toolitem12 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem12);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem12);

  butIMAddBuddy = gtk_button_new ();
  gtk_widget_show (butIMAddBuddy);
  gtk_container_add (GTK_CONTAINER (toolitem12), butIMAddBuddy);
  gtk_tooltips_set_tip (tooltips, butIMAddBuddy, _("Add to Buddy List"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butIMAddBuddy), GTK_RELIEF_NONE);

  image15 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (butIMAddBuddy), image15);

  toolitem13 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem13);
  gtk_container_add (GTK_CONTAINER (tbIMAttrib), toolitem13);

  butIgnore = gtk_button_new ();
  gtk_widget_show (butIgnore);
  gtk_container_add (GTK_CONTAINER (toolitem13), butIgnore);
  gtk_tooltips_set_tip (tooltips, butIgnore, _("Ignore User"), NULL);
  gtk_button_set_relief (GTK_BUTTON (butIgnore), GTK_RELIEF_NONE);

  image16 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (butIgnore), image16);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, TRUE, 0);

  scwIMSend = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scwIMSend);
  gtk_box_pack_start (GTK_BOX (hbox3), scwIMSend, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scwIMSend, -1, 50);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scwIMSend), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scwIMSend), GTK_SHADOW_IN);

  txtIMSend = gtk_text_view_new ();
  gtk_widget_show (txtIMSend);
  gtk_container_add (GTK_CONTAINER (scwIMSend), txtIMSend);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (txtIMSend), GTK_WRAP_WORD);

  butIMSend = gtk_button_new_with_mnemonic (_("_Send"));
  gtk_widget_show (butIMSend);
  gtk_box_pack_start (GTK_BOX (hbox3), butIMSend, FALSE, FALSE, 0);

  sbIM = gtk_statusbar_new ();
  gtk_widget_show (sbIM);
  gtk_box_pack_start (GTK_BOX (vbox3), sbIM, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) winIM, "delete_event",
                    G_CALLBACK (on_winIM_delete_event),
                    NULL);
  g_signal_connect ((gpointer) mnuConversationSave, "activate",
                    G_CALLBACK (on_mnuConversationSave_activate),
                    NULL);
  g_signal_connect ((gpointer) mnuConversationQuit, "activate",
                    G_CALLBACK (on_mnuConversationQuit_activate),
                    NULL);
  g_signal_connect ((gpointer) butIMSendFile, "clicked",
                    G_CALLBACK (on_butIMSendFile_clicked),
                    NULL);
  g_signal_connect ((gpointer) butImInvite, "clicked",
                    G_CALLBACK (on_butImInvite_clicked),
                    NULL);
  g_signal_connect ((gpointer) butSmiley, "clicked",
                    G_CALLBACK (on_butSmiley_clicked),
                    NULL);
  g_signal_connect ((gpointer) butIMFont, "clicked",
                    G_CALLBACK (on_butIMFont_clicked),
                    NULL);
  g_signal_connect ((gpointer) butIMBuzz, "clicked",
                    G_CALLBACK (on_butIMBuzz_clicked),
                    NULL);
  g_signal_connect ((gpointer) butIMAddBuddy, "clicked",
                    G_CALLBACK (on_butIMAddBuddy_clicked),
                    NULL);
  g_signal_connect ((gpointer) txtIMSend, "key_press_event",
                    G_CALLBACK (on_txtIMSend_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) butIMSend, "clicked",
                    G_CALLBACK (on_butIMSend_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (winIM, winIM, "winIM");
  GLADE_HOOKUP_OBJECT (winIM, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (winIM, mnuIM, "mnuIM");
  GLADE_HOOKUP_OBJECT (winIM, mnuConversation, "mnuConversation");
  GLADE_HOOKUP_OBJECT (winIM, mnuConversation_menu, "mnuConversation_menu");
  GLADE_HOOKUP_OBJECT (winIM, mnuConversationSave, "mnuConversationSave");
  GLADE_HOOKUP_OBJECT (winIM, separatormenuitem2, "separatormenuitem2");
  GLADE_HOOKUP_OBJECT (winIM, mnuConversationQuit, "mnuConversationQuit");
  GLADE_HOOKUP_OBJECT (winIM, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (winIM, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (winIM, scwChat, "scwChat");
  GLADE_HOOKUP_OBJECT (winIM, txtChat, "txtChat");
  GLADE_HOOKUP_OBJECT (winIM, tbIMAttrib, "tbIMAttrib");
  GLADE_HOOKUP_OBJECT (winIM, toolitem11, "toolitem11");
  GLADE_HOOKUP_OBJECT (winIM, butIMSendFile, "butIMSendFile");
  GLADE_HOOKUP_OBJECT (winIM, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (winIM, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (winIM, image18, "image18");
  GLADE_HOOKUP_OBJECT (winIM, label9, "label9");
  GLADE_HOOKUP_OBJECT (winIM, toolitem14, "toolitem14");
  GLADE_HOOKUP_OBJECT (winIM, butImInvite, "butImInvite");
  GLADE_HOOKUP_OBJECT (winIM, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (winIM, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (winIM, image19, "image19");
  GLADE_HOOKUP_OBJECT (winIM, label10, "label10");
  GLADE_HOOKUP_OBJECT (winIM, separatortoolitem11, "separatortoolitem11");
  GLADE_HOOKUP_OBJECT (winIM, toolitem8, "toolitem8");
  GLADE_HOOKUP_OBJECT (winIM, butSmiley, "butSmiley");
  GLADE_HOOKUP_OBJECT (winIM, image20, "image20");
  GLADE_HOOKUP_OBJECT (winIM, toolitem9, "toolitem9");
  GLADE_HOOKUP_OBJECT (winIM, butIMFont, "butIMFont");
  GLADE_HOOKUP_OBJECT (winIM, image12, "image12");
  GLADE_HOOKUP_OBJECT (winIM, toolitem10, "toolitem10");
  GLADE_HOOKUP_OBJECT (winIM, butIMBuzz, "butIMBuzz");
  GLADE_HOOKUP_OBJECT (winIM, image13, "image13");
  GLADE_HOOKUP_OBJECT (winIM, separatortoolitem12, "separatortoolitem12");
  GLADE_HOOKUP_OBJECT (winIM, toolitem12, "toolitem12");
  GLADE_HOOKUP_OBJECT (winIM, butIMAddBuddy, "butIMAddBuddy");
  GLADE_HOOKUP_OBJECT (winIM, image15, "image15");
  GLADE_HOOKUP_OBJECT (winIM, toolitem13, "toolitem13");
  GLADE_HOOKUP_OBJECT (winIM, butIgnore, "butIgnore");
  GLADE_HOOKUP_OBJECT (winIM, image16, "image16");
  GLADE_HOOKUP_OBJECT (winIM, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (winIM, scwIMSend, "scwIMSend");
  GLADE_HOOKUP_OBJECT (winIM, txtIMSend, "txtIMSend");
  GLADE_HOOKUP_OBJECT (winIM, butIMSend, "butIMSend");
  GLADE_HOOKUP_OBJECT (winIM, sbIM, "sbIM");
  GLADE_HOOKUP_OBJECT_NO_REF (winIM, tooltips, "tooltips");

  gtk_widget_grab_focus (txtIMSend);
  gtk_window_add_accel_group (GTK_WINDOW (winIM), accel_group);

  return winIM;
}

GtkWidget*
create_dlgAbout (void)
{
  GtkWidget *dlgAbout;
  GtkWidget *dialog_vbox2;
  GtkWidget *imgAYux;
  GtkWidget *nbAbout;
  GtkWidget *lblAppDescription;
  GtkWidget *lblAAbout;
  GtkWidget *empty_notebook_page;
  GtkWidget *lblADevelopers;
  GtkWidget *lblATranslators;
  GtkWidget *dialog_action_area1;
  GtkWidget *butAboutOk;

  dlgAbout = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlgAbout), _("About Yux"));
  gtk_window_set_position (GTK_WINDOW (dlgAbout), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_type_hint (GTK_WINDOW (dlgAbout), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (dlgAbout)->vbox;
  gtk_widget_show (dialog_vbox2);

  imgAYux = create_pixmap (dlgAbout, "yux_logo.png");
  gtk_widget_show (imgAYux);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), imgAYux, TRUE, TRUE, 0);

  nbAbout = gtk_notebook_new ();
  gtk_widget_show (nbAbout);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), nbAbout, FALSE, FALSE, 0);

  lblAppDescription = gtk_label_new (_("<span weight=\"bold\" size=\"xx-large\">Yux 0.1</span>\n\nAlternate Yahoo Messenger Client for Linux\n\nBy Pravin Paratey\n[pravinp@gmail.com]"));
  gtk_widget_show (lblAppDescription);
  gtk_container_add (GTK_CONTAINER (nbAbout), lblAppDescription);
  gtk_label_set_use_markup (GTK_LABEL (lblAppDescription), TRUE);
  gtk_label_set_justify (GTK_LABEL (lblAppDescription), GTK_JUSTIFY_CENTER);

  lblAAbout = gtk_label_new (_("About"));
  gtk_widget_show (lblAAbout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbAbout), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbAbout), 0), lblAAbout);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (nbAbout), empty_notebook_page);

  lblADevelopers = gtk_label_new (_("Developers"));
  gtk_widget_show (lblADevelopers);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbAbout), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbAbout), 1), lblADevelopers);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (nbAbout), empty_notebook_page);

  lblATranslators = gtk_label_new (_("Translators"));
  gtk_widget_show (lblATranslators);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbAbout), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbAbout), 2), lblATranslators);

  dialog_action_area1 = GTK_DIALOG (dlgAbout)->action_area;
  gtk_widget_show (dialog_action_area1);

  butAboutOk = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (butAboutOk);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgAbout), butAboutOk, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (butAboutOk, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgAbout, dlgAbout, "dlgAbout");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgAbout, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dlgAbout, imgAYux, "imgAYux");
  GLADE_HOOKUP_OBJECT (dlgAbout, nbAbout, "nbAbout");
  GLADE_HOOKUP_OBJECT (dlgAbout, lblAppDescription, "lblAppDescription");
  GLADE_HOOKUP_OBJECT (dlgAbout, lblAAbout, "lblAAbout");
  GLADE_HOOKUP_OBJECT (dlgAbout, lblADevelopers, "lblADevelopers");
  GLADE_HOOKUP_OBJECT (dlgAbout, lblATranslators, "lblATranslators");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgAbout, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dlgAbout, butAboutOk, "butAboutOk");

  return dlgAbout;
}

GtkWidget*
create_dlgCustomAway (void)
{
  GtkWidget *dlgCustomAway;
  GtkWidget *dialog_vbox3;
  GtkWidget *vbox4;
  GtkWidget *hbox6;
  GtkWidget *label7;
  GtkWidget *txtAwayMessage;
  GtkWidget *chkShowBusy;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dlgCustomAway = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlgCustomAway), _("Set Away"));
  gtk_window_set_position (GTK_WINDOW (dlgCustomAway), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_type_hint (GTK_WINDOW (dlgCustomAway), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (dlgCustomAway)->vbox;
  gtk_widget_show (dialog_vbox3);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vbox4, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox6, TRUE, TRUE, 0);

  label7 = gtk_label_new_with_mnemonic (_("_Message: "));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  txtAwayMessage = gtk_entry_new ();
  gtk_widget_show (txtAwayMessage);
  gtk_box_pack_start (GTK_BOX (hbox6), txtAwayMessage, TRUE, TRUE, 0);

  chkShowBusy = gtk_check_button_new_with_mnemonic (_("_Show Busy Icon"));
  gtk_widget_show (chkShowBusy);
  gtk_box_pack_start (GTK_BOX (vbox4), chkShowBusy, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (dlgCustomAway)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_SPREAD);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgCustomAway), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgCustomAway), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label7), txtAwayMessage);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgCustomAway, dlgCustomAway, "dlgCustomAway");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgCustomAway, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, label7, "label7");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, txtAwayMessage, "txtAwayMessage");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, chkShowBusy, "chkShowBusy");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgCustomAway, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dlgCustomAway, okbutton1, "okbutton1");

  return dlgCustomAway;
}

GtkWidget*
create_dlgSendIM (void)
{
  GtkWidget *dlgSendIM;
  GtkWidget *dialog_vbox4;
  GtkWidget *table4;
  GtkWidget *image21;
  GtkWidget *label14;
  GtkWidget *txtTargetID;
  GtkWidget *label8;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  dlgSendIM = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlgSendIM), _("Send Instant Message to"));
  gtk_window_set_position (GTK_WINDOW (dlgSendIM), GTK_WIN_POS_MOUSE);
  gtk_window_set_type_hint (GTK_WINDOW (dlgSendIM), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (dlgSendIM)->vbox;
  gtk_widget_show (dialog_vbox4);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), table4, TRUE, TRUE, 0);

  image21 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image21);
  gtk_table_attach (GTK_TABLE (table4), image21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label14 = gtk_label_new (_("Enter the Yahoo ID of the\nperson you wish to send\nan Instant message to."));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table4), label14, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  txtTargetID = gtk_entry_new ();
  gtk_widget_show (txtTargetID);
  gtk_table_attach (GTK_TABLE (table4), txtTargetID, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 1, 2);
  gtk_entry_set_max_length (GTK_ENTRY (txtTargetID), 255);

  label8 = gtk_label_new_with_mnemonic (_("_Yahoo ID"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table4), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 1, 2);

  dialog_action_area3 = GTK_DIALOG (dlgSendIM)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgSendIM), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgSendIM), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label8), txtTargetID);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgSendIM, dlgSendIM, "dlgSendIM");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgSendIM, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dlgSendIM, table4, "table4");
  GLADE_HOOKUP_OBJECT (dlgSendIM, image21, "image21");
  GLADE_HOOKUP_OBJECT (dlgSendIM, label14, "label14");
  GLADE_HOOKUP_OBJECT (dlgSendIM, txtTargetID, "txtTargetID");
  GLADE_HOOKUP_OBJECT (dlgSendIM, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgSendIM, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dlgSendIM, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dlgSendIM, okbutton2, "okbutton2");

  return dlgSendIM;
}

GtkWidget*
create_dlgAddBuddy (void)
{
  GtkWidget *dlgAddBuddy;
  GtkWidget *dialog_vbox5;
  GtkWidget *table5;
  GtkWidget *image22;
  GtkWidget *lblAddBuddy;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *txtYahooID;
  GtkWidget *cboeGroup;
  GtkWidget *txtMessage;
  GtkWidget *label16;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton3;
  GtkWidget *okbutton3;

  dlgAddBuddy = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dlgAddBuddy), _("Add Buddy"));
  gtk_window_set_type_hint (GTK_WINDOW (dlgAddBuddy), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox5 = GTK_DIALOG (dlgAddBuddy)->vbox;
  gtk_widget_show (dialog_vbox5);

  table5 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), table5, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 5);

  image22 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image22);
  gtk_table_attach (GTK_TABLE (table5), image22, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  lblAddBuddy = gtk_label_new_with_mnemonic (_("_Yahoo ID "));
  gtk_widget_show (lblAddBuddy);
  gtk_table_attach (GTK_TABLE (table5), lblAddBuddy, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblAddBuddy), 0, 0.5);

  label17 = gtk_label_new_with_mnemonic (_("_Group"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table5), label17, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new_with_mnemonic (_("_Message "));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table5), label18, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  txtYahooID = gtk_entry_new ();
  gtk_widget_show (txtYahooID);
  gtk_table_attach (GTK_TABLE (table5), txtYahooID, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (txtYahooID), 255);

  cboeGroup = gtk_combo_box_entry_new ();
  gtk_widget_show (cboeGroup);
  gtk_table_attach (GTK_TABLE (table5), cboeGroup, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  txtMessage = gtk_entry_new ();
  gtk_widget_show (txtMessage);
  gtk_table_attach (GTK_TABLE (table5), txtMessage, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label16 = gtk_label_new (_("Enter the Yahoo ID of the person you wish to add as a buddy and the group you want to place this buddy into. You can also send an optional message"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table5), label16, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label16), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0);

  dialog_action_area4 = GTK_DIALOG (dlgAddBuddy)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgAddBuddy), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dlgAddBuddy), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  gtk_label_set_mnemonic_widget (GTK_LABEL (lblAddBuddy), txtYahooID);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label18), txtMessage);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dlgAddBuddy, dlgAddBuddy, "dlgAddBuddy");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgAddBuddy, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, table5, "table5");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, image22, "image22");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, lblAddBuddy, "lblAddBuddy");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, label17, "label17");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, label18, "label18");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, txtYahooID, "txtYahooID");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, cboeGroup, "cboeGroup");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, txtMessage, "txtMessage");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (dlgAddBuddy, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (dlgAddBuddy, okbutton3, "okbutton3");

  gtk_widget_grab_default (okbutton3);
  return dlgAddBuddy;
}

