/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_winMain (void);
GtkWidget* create_dlgLogin (void);
GtkWidget* create_winIM (void);
GtkWidget* create_dlgAbout (void);
GtkWidget* create_dlgCustomAway (void);
GtkWidget* create_dlgSendIM (void);
GtkWidget* create_dlgAddBuddy (void);
